spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:application-aws.yml
      - classpath:application-credentials.yml
      - classpath:application-oauth.yml
      - classpath:application-jwt.yml
      - classpath:application-swagger.yml
      - classpath:application-rds.yml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080


